### ISSUE TITLE
aws-lambda-cpp-0.2.6 unable to be installed, preinstall.sh failure

### ISSUE THREAD

**Issue by MirandaDora** [aws/aws-lambda-nodejs-runtime-interface-client#10]
I am trying to do `RUN npm install aws-lambda-ric@1.0.0`
It fails for the following reason:
> ./scripts/preinstall.sh
`tar: aws-lambda-cpp-0.2.6/packaging: Cannot change ownership to uid XXXX, gid XXXX.`

The error appears to be when unzip aws-lambda-cpp-0.2.6 in the preinstall script.
This is not reproducible locally, but on the automatic pipleline, you can see this.

The root cause is, most of the pipelines having the limitation:
> UID/GIDs that are placed on files must be in the range 0-65535

However, the uid and gid I received is `uid 1515433866, gid 1896053708`.
May need to investigate what change has caused the ownership switch when installing aws-lambda-cpp

The quick workaround is to add `--no-same-owner` in the tar command.

Reference: https://github.com/golangci/golangci-lint/issues/752

**Comment by calavera** [comment]
problems like this would go away with #8

**Comment by donn** [comment]
Issue persists as of the time of writing.

**Comment by donn** [comment]
So, here's another workaround if you don't want to fork this repo:

```Dockerfile
RUN groupadd -g 1001 lambda
RUN useradd -r -u 1001 -g lambda lambda

RUN chown -R lambda:lambda ${FUNCTION_DIR}

USER lambda
```

A four-digit UID/GID works fine. Do note though that if anything needs root privileges you have to do it before this point. Them's the breaks.

**Comment by andclt** [comment]
This was fixed with: https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/pull/46
