### ISSUE TITLE
The build is broken for Alpine v3.20

### ISSUE THREAD

**Issue by AlexeyMoiseev** [aws/aws-lambda-nodejs-runtime-interface-client#108]
The error message:
```
27.88 npm error *** Do not use buildconf. Instead, just use: autoreconf -fi
27.88 npm error configure.ac:120: installing './compile'
27.88 npm error configure.ac:317: installing './config.guess'
27.88 npm error configure.ac:317: installing './config.sub'
27.88 npm error configure.ac:120: installing './install-sh'
27.88 npm error configure.ac:125: installing './missing'
27.88 npm error docs/examples/Makefile.am: installing './depcomp'
27.88 npm error parallel-tests: installing './test-driver'
27.88 npm error ./configure: line 6673: syntax error: unexpected ";;" (expecting "fi")
27.88 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-05-27T13_13_59_769Z-debug-0.log
```
No problem with v3.19, the error was introduced with the latest v3.20 version.

**Comment by m-rph** [comment]
Identical issue to https://github.com/aws/aws-lambda-python-runtime-interface-client/issues/145

**Comment by swantzter** [comment]
Same on Arch Linux

**Comment by nykma** [comment]
After some digging on Nix build system, I found that if `autoconf` is locked on `2.71` (`pkgs.autoconf271`) , everything works fine. 

Alpine 3.20 updated `autoconf` from `2.71` to `2.72`, think this might be the reason.

**Comment by m-rph** [comment]
Hi, this is a known issue that affects all runtimes that currently use the native (C++ client).
Quoting [this comment](https://github.com/aws/aws-lambda-python-runtime-interface-client/issues/144#issuecomment-2230586114):

> Hi, we are aware of the issue.
> 
> This is caused by the dependency on libcurl and the update on autoconf. We use libcurl to ensure consistent performance and minimize overhead. The update on autoconf included a change that broke some macros defined in the libcurl version used by the runtime interface client.
> 
> Our current recommendation is to pin the autoconf version with the provided work-around.

That is to say, pinning autoconf to 2.71 will fix the issue.

Thanks,
Quinn

**Comment by swantzter** [comment]
I've gotten to a working spot by downgrading to alpine 3.19 to get a) autoconf 2.17, b) pthon 3.11 (node-gyp 9 is broken for python >= 3.12)

This mess seems to work at least
```Dockerfile
FROM node:20-alpine3.19 AS base
RUN apk update -q && apk upgrade
RUN apk add autoconf automake cmake g++ libtool make unzip curl-dev python3
RUN apk add --no-cache --update --repository=https://dl-cdn.alpinelinux.org/alpine/v3.16/main/ libexecinfo-dev
```

**Comment by daverickdunn** [comment]
I gave up on alpine and managed to get debian 12 to work, though it too had the same error initially.

```dockerfile
FROM mcr.microsoft.com/powershell:7.4-debian-12

RUN apt update
RUN apt upgrade -y

RUN apt install nodejs npm g++ make cmake unzip libcurl4-openssl-dev automake libtool -y
```

**Comment by m-rph** [comment]
Hi everyone, we've merged a patch on python that fixes this issue, we will be porting to this one promptly.

Quinn
