### ISSUE TITLE
Binary does not work and create a coredump

### ISSUE THREAD

**Issue by KnisterPeter** [aws/aws-lambda-nodejs-runtime-interface-client#119]
After installing this package and starting it, it fails with the following error:

```
Executing 'index.handler' in function directory '/test'
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

Tested on different docker base images (node:20-slim, node:22-slim), doesn't matter.

**Comment by m-rph** [comment]
Hi, could you provide a sample function? This issue comes up when the handler is inaccessible. Perhaps it's not exported?

**Comment by KnisterPeter** [comment]
After going through all closed issues, I think it's this one: https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/issues/101
If at all possible, the error message could be better 😄

**Comment by KnisterPeter** [comment]
Should we close it?

**Comment by m-rph** [comment]
Thanks, closing as resolved.

We will add these in a FAQ section to avoid any future confusion.

Thank you.
