### ISSUE TITLE
Missing Runtime API Server configuration Error while deploying to docker

### ISSUE THREAD

**Issue by vigneshtdev** [aws/aws-lambda-nodejs-runtime-interface-client#15]
Here's my docker file

```
FROM node:14.16.0-buster as build-image


  # Include global arg in this stage of the build

  # Install aws-lambda-cpp build dependencies
  RUN apt-get update && \
      apt-get install -y \
      g++ \
      make \
      cmake \
      unzip \
      libcurl4-openssl-dev

  RUN apt-get install -y libwoff1 \
                           libopus0 \
                           libwebp6 \
                           libwebpdemux2 \
                           libenchant1c2a \
                           libgudev-1.0-0 \
                           libsecret-1-0 \
                           libhyphen0 \
                           libgdk-pixbuf2.0-0 \
                           libegl1 \
                           libnotify4 \
                           libxslt1.1 \
                           libevent-2.1-6 \
                           libgles2 \
                           libgl1 \
                           libvpx5 \
                           # for chromium
                           libnss3 \
                           libxss1 \
                           libasound2 \
                           # for firefox
                           libdbus-glib-1-2 \
                           libxt6


  COPY app.js package.json /var/task/

  WORKDIR /var/task

  RUN npm install

  ENTRYPOINT ["/usr/local/bin/npx", "aws-lambda-ric"]
  CMD [ "app.handler" ]
```
app.js
```
"use strict";

  const { firefox } = require('playwright-firefox');

  const run = async () => {
      const browser = await firefox.launch({headless: true},);
      console.log(browser.version);
      const page = await browser.newPage();
      await page.goto('https://google.com/');
      //new S3().upload(await page.screenshot({ path: `example.png` }));
      await browser.close();
  }


  exports.handler = async (event, context) => {
      console.log(event);

      console.log(process.platform);
      await run();
      return "Success";
  };
```

**Comment by carlzogh** [comment]
Hey @vigneshtdev - I believe you are referring to local testing of the RIC not working and this would be because of a missing Runtime API Server when you're trying to run the function. For local testing scenarios, I'd recommend having a look at the AWS Documentation on [Testing Lambda container images locally](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html) with the [Runtime Interface Emulator](https://github.com/aws/aws-lambda-runtime-interface-emulator).

Does the image run successfully when invoked within Lambda?

**Comment by alexey2baranov** [comment]
I wonder if someone can understand Runtime - Runtime API - Runtime API Emulator - RIC - etc combination 
AWS Lambda very easy to understand in promo  but very hard to work  :( 
Im trying to test very simple task last three days. Without AWS Lambda I can do this in a few minutes.

@carlzogh  Maybe you can give me a peace of advice how to do this shortly?

**Comment by umarta85** [comment]
@vigneshtdev @carlzogh @alexey2baranov anybody managed to solve this? Facing the same problem

**Comment by alexey2baranov** [comment]
@umarta85 no :(

**Comment by uavdrip** [comment]
@alexey2baranov Sad to hear that..

**Comment by fcoury** [comment]
Facing the same issue

**Comment by jlarmstrongiv** [comment]
These examples helped me a lot:
- https://stackoverflow.com/a/72157875
- https://docs.aws.amazon.com/lambda/latest/dg/images-test.html

**Comment by andclt** [comment]
Hi,
In our README we have a section about [local testing](https://github.com/aws/aws-lambda-nodejs-runtime-interface-client#local-testing).

There are multiple ways to test a Lambda container image locally. They are described in more detail here: https://docs.aws.amazon.com/lambda/latest/dg/images-test.html#images-test-alternative
