### ISSUE TITLE
RIC and Distroless base images

### ISSUE THREAD

**Issue by seano-vs** [aws/aws-lambda-nodejs-runtime-interface-client#21]
Hey everyone-
Really enjoying all of this so far. I have this working just fine with the Python RIC, but running into a few issues with trying to get it to execute on [distroless/nodejs:14](https://github.com/GoogleContainerTools/distroless/blob/main/nodejs/README.md) as the final base image. Does anyone have a suggested best practice for executing the RIC without npx? Here is my Dockerfile thus far:

```dockerfile
ARG FUNCTION_DIR="/function"
FROM node:14-buster as build-image
ARG FUNCTION_DIR
RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev
RUN mkdir -p ${FUNCTION_DIR}
COPY * ${FUNCTION_DIR}
WORKDIR ${FUNCTION_DIR}
RUN npm install

FROM gcr.io/distroless/nodejs:14
ARG FUNCTION_DIR
WORKDIR ${FUNCTION_DIR}
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}
# Naturally, the below doesn't work. 
ENTRYPOINT ["/usr/local/bin/npx", "aws-lambda-ric"]
CMD ["app.handler"]
```

Any ideas? For obvious reasons, any attempts at having the npx binary play ball are unsuccessful.

**Comment by zzolo** [comment]
`npx` should come with `npm` which should be installed with the Node package, which I assume is already there given the `FROM` is `node-14`.

**Comment by seano-vs** [comment]
For anyone else wondering, I had some extra help swoop in and we figured it out. Everything else above should stay the same, but remove the ENTRYPOINT and CMD and use this:

`CMD [ "./node_modules/.bin/aws-lambda-ric", "app.handler" ]`

Naturally, RIE is needed to test locally.
