### ISSUE TITLE
Feature Request: Support for ES Modules

### ISSUE THREAD

**Issue by nickcox** [aws/aws-lambda-nodejs-runtime-interface-client#22]
[Afaict](https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/5c92d9bbeed0e9db836a0cc12cbc57135745a200/src/utils/UserFunction.ts#L75), there's no way to use an ES module based hander right now.

It would be awesome to have one less build step. Just wondering if this is on the roadmap?

**Comment by jimmywarting** [comment]
This code needs to be aware if the package.json has `"type": "module"` and if it is... then it needs to use dynamic import `import(path)` instead
https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/c31c41ffe5f2f03ae9e8589b96f3b005e2bb8a4a/src/utils/UserFunction.ts#L70-L87

but b/c you use typescript and downlevel everything to commonjs 👎 then you need to use:
```js
const _importDynamic = new Function('modulePath', 'return import(modulePath)')
_importDynamic(path)
```

(Imo i think you should ditch typescript, switch to ESM and not transpile anything - but this is just my opinion)

**Comment by krk** [comment]
This is fixed in https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/pull/70.
