### ISSUE TITLE
getRemainingTimeInMillis is returning NaN.

### ISSUE THREAD

**Issue by ramaguruprakash** [aws/aws-lambda-nodejs-runtime-interface-client#33]
We created a custom docker image for lambda with the following dockerFile.

DockerFile
ARG FUNCTION_DIR="/code"
FROM node:12-buster as build-image

ARG FUNCTION_DIR

RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev

RUN npm -g config set user root
RUN npm install -g aws-lambda-ric
RUN npm -g config set user nobody

RUN mkdir -p ${FUNCTION_DIR}
COPY . ${FUNCTION_DIR}
RUN chmod -R 775 ${FUNCTION_DIR}
WORKDIR ${FUNCTION_DIR}
ENTRYPOINT exec /usr/local/bin/npx aws-lambda-ric index.handler

When we print the getRemainingTimeInMillis, we get the value as NaN.

We tried to print the function itself and got the following response.

`function () { return deadline - Date.now(); }`

As we missing anything here ?

**Comment by vamshikolanu** [comment]
Hello, is there any update regarding this?

**Comment by janakg** [comment]
any updates?

**Comment by XMegamanX** [comment]
Hello there ! Same issue ! Have you found a workaround ? Thanks

**Comment by XMegamanX** [comment]
I have found the problem, just add the env variable AWS_LAMBDA_NODEJS_USE_ALTERNATIVE_CLIENT_1 = true to the Lambda Configuration. It makes the trick :)

**Comment by andclt** [comment]
Hi,

I am not able to get this issue with the latest `aws-lambda-ric` version (`v3.0.0`). 

```
console.log(context.getRemainingTimeInMillis());

INFO	2693
```

Feel free to reopen it if you still face this issue with the latest version.
