### ISSUE TITLE
ES module support

### ISSUE THREAD

**Issue by majg0** [aws/aws-lambda-nodejs-runtime-interface-client#44]
https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/

Also; is this maintained? Last commit Nov 3 2021, open issues and outstanding PRs.

**Comment by darrinholst** [comment]
So cracking open the latest `amazon/aws-lambda-nodejs` image I see this in UserFunction.js...

``` javascript
  // If still not loaded, try .js, .mjs, and .cjs in that order.
  // Files ending with .js are loaded as ES modules when the nearest parent package.json
  // file contains a top-level field "type" with a value of "module".
  // https://nodejs.org/api/packages.html#packages_type
  const loaded =
    (pjHasModule && _tryAwaitImport(lambdaStylePath, ".js")) ||
    _tryAwaitImport(lambdaStylePath, ".mjs") ||
    _tryRequireFile(lambdaStylePath, ".cjs");
```

so it looks to have been added, but hasn't made it up to this repo yet?

**Comment by tforster** [comment]
It's now more than halfway through June. Is there any update on this issue? It's pretty critical not to be able to use ES modules in 2022.

**Comment by daniel-gato** [comment]
Same here, we need this asap.

**Comment by govindrai** [comment]
Don't want to repeat the same request but it would be great it to get some response from maintainers

**Comment by krk** [comment]
This is fixed in https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/pull/70.
